server:
  port: :8080
database:
  driver: postgres
  host: localhost
  port: 5432
  user: example_user
  password: example_password
  dbname: example_dbname
  sslmode: disable
  maxopenconn: 20
  maxidleconn: 10
  maxidletime: 15m
